name: tilebasedwordsearch
description: GAME
version: 0.1.0
author: Dart DevRel
homepage: https://github.com/johnmccutchan/tilebasedwordsearch
dependencies:
  unittest: any
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  browser: any
  web_ui: any
  buildtool:
    git:
      url: git://github.com/dart-lang/buildtool.git
      ref: "m4"
