name: tilebasedwordsearch
description: GAME
version: 0.1.0
author: Dart DevRel
homepage: https://github.com/johnmccutchan/tilebasedwordsearch
dependencies:
  unittest: any
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  browser: any
  web_ui: any
  benchmark_harness: any
  lawndart: any