name: tilebasedwordsearch
description: GAME
version: 0.1.0
author: Dart DevRel
homepage: https://github.com/johnmccutchan/tilebasedwordsearch
dependencies:
  unittest: any
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  browser: any
  web_ui: any
  benchmark_harness: any
  lawndart: any
  postgresql: any
  start: any
  google_plus_v1_api: any
  google_games_v1_api:
    git: git://github.com/financeCoding/dart_games_v1_api_client.git
  google_appstate_v1_api:
    git: git://github.com/financeCoding/dart_appstate_v1_api_client.git
  logging: any
