name: tilebasedwordsearch
version: 0.1.0
author: Dart DevRel
description: GAME
homepage: https://github.com/johnmccutchan/tilebasedwordsearch
dependencies:
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  benchmark_harness: any
  browser: any
  crypto: any
  fukiya: '>=0.1.5'
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  google_appstate_v1_api:
    git: https://github.com/financeCoding/dart_appstate_v1_api_client.git
  google_games_v1_api:
    git: https://github.com/financeCoding/dart_games_v1_api_client.git
  google_plus_v1_api:
    git: https://github.com/financeCoding/dart_plus_v1_api_client.git
  html5lib: any
  http: any
  intl: any
  lawndart: any
  logging: any
  postgresql: any
  start: any
  unittest: any
  web_ui: any
